name: Run Ruff

on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run Ruff
        uses: astral-sh/ruff-action@v1
        with:
          args: "."
          src: "./src"