on: [push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    name: "ruff"
    steps:
      - uses: davidslusser/actions_python_ruff@v1.0.0
        with:
          pip_install_command: "pip install ruff"
          python_version: "3.12"
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install pylint
      - name: Run Ruff with specific rule ignored
        run: |
          ruff --ignore=E722
